/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js. It is committed here so initial typechecks
// work before the dev server has been run.
